$(document).ready(function(){$('#nav-login').submit(function(){var dados=jQuery(this).serialize();$.ajax({type:"POST",url:"sistema/authhandler.php",data:dados,cache:false,beforeSend:function(){$("#aviso").hide();$("#aviso").html("");$("#loading").show();$("#loading").html('<center><img src=\"img/ajax-loader.gif\"></center>');},success:function(data){if(data==true){location.reload();}else{$("#loading").hide();$("#aviso").show();$("#aviso").html("Usuário ou senha incorretos");}}})
return false;})
$('#modal-login').submit(function(){var dados=jQuery(this).serialize();$.ajax({type:"POST",url:"sistema/authhandler.php",data:dados,cache:false,beforeSend:function(data){$("#avisom").hide();$("#avisom").html("");$("#loadingm").show();$("#loadingm").html('<center><img src=\"img/ajax-loader.gif\"></center>');},success:function(data){if(data==true){location.reload();}else{$("#loadingm").hide();$("#avisom").show();$("#avisom").html("Usuário ou senha incorretos");}}})
return false;})
function valida(form){if(form.email.value==""){alert("Preencha o e-mail corretamente.");return false;}
if(form.termos.checked==false){alert("É necessário concordar com os Termos VIP.");return false;}}
$(function(){$('#menulateral').on('click','.list-group-item',function(e){e.preventDefault();$(this).parents('#menulateral').find('.active').removeClass('active').end().end().addClass('active');});});$('[data-toggle="tooltip"]').tooltip();var interval=10000;var refresh=function(){$.getJSON("https://mcapi.ca/query/jogar.mithcraft.com.br/players",function(json){if(json.status!==true){$(".infobar").text('SERVIDOR OFFLINE').addClass('server-error');}else{$("#jo").html(json.players.online);}});setTimeout(function(){refresh();},interval);};refresh();$("[data-acao='vantagens']").click(function(){gerarVantagens($(this).attr('id'));});$("[data-acao='pagar']").click(function(){gerarModalPagamento($(this).attr('id'),$(this).attr('data-metodo'),$(this).attr('data-tipo'));});function gerarModalPagamento(pacote,metodo,tipo){$.ajax({type:"POST",url:'sistema/geradores.php',dataType:'html',data:'acao=pagar'+'&metodo='+ metodo+'&tipo='+ tipo+'&pacote='+ pacote,beforeSend:function(){if(tipo==='outros'){$("#modalconteudooutros").html('<hr><center><img src=\"img/ajax-loader.gif\"></center><hr>');}
$("#modalconteudo").html('<hr><center><img src=\"img/ajax-loader.gif\"></center><hr>');},success:function(data){if(tipo==='outros'){$("#modalconteudooutros").html(data);}
$("#modalconteudo").html(data);},error:function(){if(tipo==='outros'){$("#modalconteudooutros").html('<hr><center>Erro! Por favor atualize a pagina.</center><hr>');}
$("#modalconteudo").html('<hr><center>Erro! Por favor atualize a pagina.</center><hr>');}});}
function gerarVantagens(pacote){$.ajax({type:"POST",url:'sistema/geradores.php',dataType:'html',data:'acao=vantagens'+'&pacote='+ encodeURIComponent(pacote),beforeSend:function(){$("#modalconteudov").html('<hr><center><img src=\"img/ajax-loader.gif\"></center><hr>');},success:function(data){$("#modalconteudov").html(data);},error:function(){$("#modalconteudov").html('<hr><center>Erro! Por favor atualize a pagina.</center><hr>');}});}
$('[data-tooltip="tooltip"]').tooltip();});